### ISSUE TITLE
REPORTE_APP_DISEÑO_XD

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practicaprototipos-team-check#3]
[TOPICOS_AVANZADOS_REPORTE_EN_EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-team-check/files/6161349/TOPICOS_AVANZADOS_REPORTE_EN_EQUIPO.pdf)

**Comment by Anthony4523** [comment]
Calificación obtenida: 90/100
Buen trabajo compañeros

**Comment by Eva155** [comment]
CALIFICACIÓN CORREGIDA
Calificación: 18 puntos

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
