### ISSUE TITLE
Practica_PDF_CALCULADORA_REPORTE

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practicaprototipos-team-check#4]
[Práctica Calculadora Equipo Cheak! Team.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-team-check/files/6161866/Practica.Calculadora.Equipo.Cheak.Team.pdf)

**Comment by Anthony4523** [comment]
Calificación obtenida: 100/100
Excelente trabajo compañeros :)

**Comment by Eva155** [comment]
CALIFICACIÓN CORREGIDA
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
